services:
  tomcat:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/sms:/usr/local/tomcat/webapps/sms
      # - ./src/main/webapp:/usr/local/tomcat/webapps/sms
      # - ./src/main/java:/usr/local/tomcat/webapps/sms/java
      - ./logs:/usr/local/tomcat/logs
