services:
  tomcat:
    image: tomcat:jdk21
    container_name: tomcat
    command: "catalina.sh run"
    ports:
      - "8080:8080"
    volumes:
      - ./target/sms:/usr/local/tomcat/webapps/sms
      - ./logs:/usr/local/tomcat/logs
