# services:
#   tomcat:
#     image: tomcat:10.1.26-jre21
#     build:
#       context: '.'

#     container_name: tomcat
#     ports:
#       - "8080:8080"
#     volumes:
#       # - ./src:/usr/local/tomcat/webapps  # Persist webapps directory
#       - ./src/main/webapp:/usr/local/tomcat/webapps/sms  # Persist webapps directory
#       - ./conf:/usr/local/tomcat/conf  # Persist configuration files
#       - ./logs:/usr/local/tomcat/logs
# volumes: {}
#   # src:
#   # conf:

services:
  tomcat:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/sms
      - ./logs:/usr/local/tomcat/logs
